{% set name = "openapi-pydantic" %}
{% set version = "0.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/openapi_pydantic-{{ version }}.tar.gz
  sha256: a48f88e2904a056e1ef6d4728cfb2f36aa3213ce194fb09fc04259b9007165f0

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8,<4.0
    - poetry-core >=1.0.0
    - pip
  run:
    - python >=3.8.0,<4.0.0
    - pydantic >=1.8

test:
  imports:
    - openapi_pydantic
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/mike-oakley/openapi-pydantic
  summary: Pydantic OpenAPI schema implementation
  license: MIT
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - thewchan
